/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.hawk.service.api;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-08-17")
public class HawkSynchronizationStartEvent implements org.apache.thrift.TBase<HawkSynchronizationStartEvent, HawkSynchronizationStartEvent._Fields>, java.io.Serializable, Cloneable, Comparable<HawkSynchronizationStartEvent> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HawkSynchronizationStartEvent");

  private static final org.apache.thrift.protocol.TField TIMESTAMP_NANOS_FIELD_DESC = new org.apache.thrift.protocol.TField("timestampNanos", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HawkSynchronizationStartEventStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HawkSynchronizationStartEventTupleSchemeFactory());
  }

  public long timestampNanos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIMESTAMP_NANOS((short)1, "timestampNanos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIMESTAMP_NANOS
          return TIMESTAMP_NANOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMPNANOS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIMESTAMP_NANOS, new org.apache.thrift.meta_data.FieldMetaData("timestampNanos", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HawkSynchronizationStartEvent.class, metaDataMap);
  }

  public HawkSynchronizationStartEvent() {
  }

  public HawkSynchronizationStartEvent(
    long timestampNanos)
  {
    this();
    this.timestampNanos = timestampNanos;
    setTimestampNanosIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HawkSynchronizationStartEvent(HawkSynchronizationStartEvent other) {
    __isset_bitfield = other.__isset_bitfield;
    this.timestampNanos = other.timestampNanos;
  }

  public HawkSynchronizationStartEvent deepCopy() {
    return new HawkSynchronizationStartEvent(this);
  }

  @Override
  public void clear() {
    setTimestampNanosIsSet(false);
    this.timestampNanos = 0;
  }

  public long getTimestampNanos() {
    return this.timestampNanos;
  }

  public HawkSynchronizationStartEvent setTimestampNanos(long timestampNanos) {
    this.timestampNanos = timestampNanos;
    setTimestampNanosIsSet(true);
    return this;
  }

  public void unsetTimestampNanos() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMPNANOS_ISSET_ID);
  }

  /** Returns true if field timestampNanos is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestampNanos() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMPNANOS_ISSET_ID);
  }

  public void setTimestampNanosIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMPNANOS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TIMESTAMP_NANOS:
      if (value == null) {
        unsetTimestampNanos();
      } else {
        setTimestampNanos((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TIMESTAMP_NANOS:
      return getTimestampNanos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TIMESTAMP_NANOS:
      return isSetTimestampNanos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HawkSynchronizationStartEvent)
      return this.equals((HawkSynchronizationStartEvent)that);
    return false;
  }

  public boolean equals(HawkSynchronizationStartEvent that) {
    if (that == null)
      return false;

    boolean this_present_timestampNanos = true;
    boolean that_present_timestampNanos = true;
    if (this_present_timestampNanos || that_present_timestampNanos) {
      if (!(this_present_timestampNanos && that_present_timestampNanos))
        return false;
      if (this.timestampNanos != that.timestampNanos)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_timestampNanos = true;
    list.add(present_timestampNanos);
    if (present_timestampNanos)
      list.add(timestampNanos);

    return list.hashCode();
  }

  @Override
  public int compareTo(HawkSynchronizationStartEvent other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTimestampNanos()).compareTo(other.isSetTimestampNanos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestampNanos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestampNanos, other.timestampNanos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HawkSynchronizationStartEvent(");
    boolean first = true;

    sb.append("timestampNanos:");
    sb.append(this.timestampNanos);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'timestampNanos' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HawkSynchronizationStartEventStandardSchemeFactory implements SchemeFactory {
    public HawkSynchronizationStartEventStandardScheme getScheme() {
      return new HawkSynchronizationStartEventStandardScheme();
    }
  }

  private static class HawkSynchronizationStartEventStandardScheme extends StandardScheme<HawkSynchronizationStartEvent> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HawkSynchronizationStartEvent struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIMESTAMP_NANOS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestampNanos = iprot.readI64();
              struct.setTimestampNanosIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTimestampNanos()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestampNanos' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HawkSynchronizationStartEvent struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TIMESTAMP_NANOS_FIELD_DESC);
      oprot.writeI64(struct.timestampNanos);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HawkSynchronizationStartEventTupleSchemeFactory implements SchemeFactory {
    public HawkSynchronizationStartEventTupleScheme getScheme() {
      return new HawkSynchronizationStartEventTupleScheme();
    }
  }

  private static class HawkSynchronizationStartEventTupleScheme extends TupleScheme<HawkSynchronizationStartEvent> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HawkSynchronizationStartEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.timestampNanos);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HawkSynchronizationStartEvent struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.timestampNanos = iprot.readI64();
      struct.setTimestampNanosIsSet(true);
    }
  }

}

