/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.hawk.service.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum IFCExportStatus implements org.apache.thrift.TEnum {
  CANCELLED(0),
  DONE(1),
  FAILED(2),
  RUNNING(3),
  SCHEDULED(4);

  private final int value;

  private IFCExportStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static IFCExportStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return CANCELLED;
      case 1:
        return DONE;
      case 2:
        return FAILED;
      case 3:
        return RUNNING;
      case 4:
        return SCHEDULED;
      default:
        return null;
    }
  }
}
